/**
 * Canonical FRAG guild roster. War data in data.js should only include these members
 * (plus GUILD_NAME_ALIASES for alternate in-game spellings).
 */
window.GUILD_ROSTER = [
  "Afary",
  "Aozora",
  "Apocolypse_Crew",
  "Atmospheric",
  "Baakuugeki",
  "Beights",
  "Belserion",
  "Centurien",
  "CheekyBigKahuna",
  "Clan_Ellis",
  "CM_Yami",
  "Coldest",
  "Coldsin",
  "Conlaoch",
  "Darkiden",
  "DDE",
  "Degens77",
  "Deroxide",
  "Dragoneel",
  "DrShortstuf",
  "Eight76",
  "Extragalactic",
  "FleitesFamily",
  "FxAxFxO",
  "GodsRNG",
  "GodZeebo",
  "GONXTA",
  "Great_Nazaricks",
  "Grimz",
  "Hendo1114",
  "Hersheyyy",
  "HolyTrinity",
  "HouseofShield",
  "Hypnotica",
  "Iarsen",
  "IEtherealI",
  "IHydrex",
  "Ikaroswolf",
  "Infernorage",
  "Interventionz",
  "Jaycro",
  "Jazz1118",
  "Jdark25",
  "Jeggings",
  "Jetsecan",
  "JoseFist",
  "Kagome",
  "Kilzuras",
  "Kinyon15",
  "Kitsune",
  "Koisenso",
  "KOONandFriends",
  "Ktcuda",
  "Kurisumasu",
  "Kyln",
  "Lord_Blaze",
  "LordGrim",
  "Marszarukky",
  "MoonlitMocha",
  "MyFamilyName",
  "Mythal",
  "NemesisProgram",
  "Netsrik",
  "Odaa",
  "Okami",
  "PickleRick69",
  "PinguFamily",
  "Plaiddisco",
  "Ragna_Crimson",
  "RealBanger",
  "REMEDY94",
  "Renegade69",
  "Rxckless",
  "Shadowfang",
  "ShottaZz",
  "SinfulxJudgement",
  "Sunsorian",
  "SuperSenior",
  "Suspex",
  "TheRossSauce",
  "Trackstarriq",
  "Treehugger",
  "Trooperr",
  "Ulskay",
  "Umassoura",
  "Umbrella",
  "Unagote",
  "Unknown_VII",
  "Witchico",
  "Worlboss",
  "XChronik",
  "XOdaaX",
  "XxCASHxX",
  "Yuki_Chan",
];

/** War result spelling → canonical roster name */
window.GUILD_NAME_ALIASES = {
  larsen: "Iarsen",
  CM_YAMI: "CM_Yami",
  IHydrexI: "IHydrex",
  IHydrexl: "IHydrex",
  IEthereall: "IEtherealI",
  KOOONandFRIENDS: "KOONandFriends",
};
