/**
 * Canonical FRAG guild roster. War data in data.js should only include these members
 * (plus GUILD_NAME_ALIASES for alternate in-game spellings).
 */
window.GUILD_ROSTER = [
  "Afary",
  "Aozora",
  "Apocolypse_Crew",
  "Atmospheric",
  "Baakuugeki",
  "Beights",
  "Centurien",
  "CheekyBigKahuna",
  "Clan_Ellis",
  "CM_Yami",
  "Coldest",
  "Coldsin",
  "Conlaoch",
  "Darkiden",
  "DDE",
  "Deroxide",
  "Dragoneel",
  "DrShortstuf",
  "Eight76",
  "Extragalactic",
  "FleitesFamily",
  "FxAxFxO",
  "GodsRNG",
  "GodZeebo",
  "GONXTA",
  "Great_Nazaricks",
  "Grimz",
  "Hendo1114",
  "Hersheyyy",
  "HolyTrinity",
  "HouseofShield",
  "Hypnotica",
  "Iarsen",
  "IEtherealI",
  "IHydrex",
  "Ikaroswolf",
  "Infernorage",
  "Interventionz",
  "Jaycro",
  "Jazz1118",
  "Jdark25",
  "Jeggings",
  "Jetsecan",
  "JoseFist",
  "Kagome",
  "Kilzuras",
  "Kinyon15",
  "Kitsune",
  "Koisenso",
  "KOONandFriends",
  "Kurisumasu",
  "Kyln",
  "Lord_Blaze",
  "LordGrim",
  "Marszarukky",
  "MoonlitMocha",
  "Musin",
  "MyFamilyName",
  "Mythal",
  "NemesisProgram",
  "Netsrik",
  "Odaa",
  "Okami",
  "PickleRick69",
  "PinguFamily",
  "Plaiddisco",
  "RealBanger",
  "REMEDY94",
  "Renegade69",
  "Rxckless",
  "Shadowfang",
  "ShottaZz",
  "SinfulxJudgement",
  "Sunsorian",
  "SuperSenior",
  "Suspex",
  "TheRossSauce",
  "Trackstarriq",
  "Treehugger",
  "Trooperr",
  "Ulskay",
  "Umassoura",
  "Umbrella",
  "Unagote",
  "Unknown_VII",
  "Witchico",
  "Worlboss",
  "XChronik",
  "XOdaaX",
  "XxCASHxX",
  "Yuki_Chan",
];

/** Member family name → team (Ball | Defense | Sailor) */
window.GUILD_MEMBER_TEAMS = {
  Afary: "Ball",
  Aozora: "Ball",
  Apocolypse_Crew: "Ball",
  Atmospheric: "Ball",
  Baakuugeki: "Ball",
  Beights: "Ball",
  Centurien: "Ball",
  CheekyBigKahuna: "Ball",
  Clan_Ellis: "Ball",
  CM_Yami: "Ball",
  Coldest: "Ball",
  Coldsin: "Ball",
  Conlaoch: "Ball",
  Darkiden: "Ball",
  DDE: "Ball",
  Deroxide: "Defense",
  Dragoneel: "Ball",
  DrShortstuf: "Ball",
  Eight76: "Ball",
  Extragalactic: "Ball",
  FleitesFamily: "Ball",
  FxAxFxO: "Ball",
  GodsRNG: "Ball",
  GodZeebo: "Ball",
  GONXTA: "Ball",
  Great_Nazaricks: "Ball",
  Grimz: "Ball",
  Hendo1114: "Sailor",
  Hersheyyy: "Ball",
  HolyTrinity: "Ball",
  HouseofShield: "Ball",
  Hypnotica: "Ball",
  Iarsen: "Ball",
  IEtherealI: "Defense",
  IHydrex: "Ball",
  Ikaroswolf: "Ball",
  Infernorage: "Ball",
  Interventionz: "Defense",
  Jaycro: "Ball",
  Jazz1118: "Ball",
  Jdark25: "Ball",
  Jeggings: "Sailor",
  Jetsecan: "Ball",
  JoseFist: "Ball",
  Kagome: "Ball",
  Kilzuras: "Ball",
  Kinyon15: "Sailor",
  Kitsune: "Ball",
  Koisenso: "Ball",
  KOONandFriends: "Ball",
  Kurisumasu: "Defense",
  Kyln: "Ball",
  Lord_Blaze: "Sailor",
  LordGrim: "Ball",
  Marszarukky: "Ball",
  MoonlitMocha: "Defense",
  Musin: "Ball",
  MyFamilyName: "Sailor",
  Mythal: "Sailor",
  NemesisProgram: "Ball",
  Netsrik: "Defense",
  Odaa: "Ball",
  Okami: "Defense",
  PickleRick69: "Ball",
  PinguFamily: "Ball",
  Plaiddisco: "Ball",
  RealBanger: "Ball",
  REMEDY94: "Ball",
  Renegade69: "Ball",
  Rxckless: "Ball",
  Shadowfang: "Defense",
  ShottaZz: "Ball",
  SinfulxJudgement: "Defense",
  Sunsorian: "Ball",
  SuperSenior: "Ball",
  Suspex: "Sailor",
  TheRossSauce: "Ball",
  Trackstarriq: "Ball",
  Treehugger: "Sailor",
  Trooperr: "Ball",
  Ulskay: "Ball",
  Umassoura: "Ball",
  Umbrella: "Ball",
  Unagote: "Defense",
  Unknown_VII: "Ball",
  Witchico: "Ball",
  Worlboss: "Defense",
  XChronik: "Defense",
  XOdaaX: "Ball",
  XxCASHxX: "Ball",
  Yuki_Chan: "Ball",
};

/** War result spelling → canonical roster name */
window.GUILD_NAME_ALIASES = {
  larsen: "Iarsen",
  CM_YAMI: "CM_Yami",
  IHydrexI: "IHydrex",
  IHydrexl: "IHydrex",
  IEthereall: "IEtherealI",
  KOOONandFRIENDS: "KOONandFriends",
};
